name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
      name: Run Unit Tests
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        - name: Instrumentation Tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            target: default
            arch: x86
            profile: Nexus 6
            script: ./gradlew connectedCheck --stacktrace
        - name: Upload Reports
          uses: actions/upload-artifact@v2
          with:
            name: Test-Reports
            path: app/build/reports
          if: always()
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          distribution: 'temurin'
          cache: gradle
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
  
